import Head from 'next/head'

const Layout = ({title, children}) => {
  return (
    <div>
      <Head>
        <title>Guitar&apos;s {title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <p>layout...</p>
      {children}
    </div>
  )
}

export default Layout
