import Head from 'next/head'
import Footer from './Footer'
import Header from './Header'

const Layout = ({title, children}) => {
  return (
    <div>
      <Head>
        <title>Guitar&apos;s {title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  )
}

export default Layout
