import Head from 'next/head'
import Footer from './Footer'
import Header from './Header'

const Layout = ({children, page}) => {
  return (
    <div>
      <Head>
        <title>Guitar {page}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin />
        <link
          href='https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;1,100;1,200&family=Poiret+One&family=Quicksand:wght@300&display=swap'
          rel='stylesheet'
        />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  )
}

export default Layout
